# Generated by Django 6.0.4 on 2026-04-27 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_damageinvoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('pending', 'Очікує'), ('approved', 'Підтверджено'), ('rejected', 'Відхилено'), ('active', 'Активне'), ('damage_pending', 'Очікує оплату ремонту'), ('returned', 'Повернено'), ('closed', 'Закрито')], default='pending', max_length=20),
        ),
    ]
